# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-creds
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:ts4bOOw=,iv:Flx2yCfb1oIIyyy78jO+ofc3ZN8HYqXl3h4eLaDqock=,tag:ts+pnMJp+w5uQNLeoowvWA==,type:str]
    admin-password: ENC[AES256_GCM,data:7NrHRrID9Q==,iv:XX9H6IZq0l8pFU9HnDA1RXwux0ChDR4RJPz0jNkseD4=,tag:oMpU5IEIC3gld1BSLsTw5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-06-25T09:36:56Z"
    mac: ENC[AES256_GCM,data:HFxEVst8rtKqeA4J+3tO1XB99Z+CEGucCpXTBSHlSDHQ+hq1fl+XzMD6RKbWPrilmA1jj9l1rDGth1OD9pay25QN+oIbIgwCYxjvH8dvMA7MRDOPIZfU0+TGxUhy4Ec2XPHoAR5Q4wDpVaVXiJSXeJtFRYt4wxiIsMbU+kbmzUY=,iv:srRkAQwI4VOSbpXabEjn/9hej8a/VIn80O/EaXMBmsQ=,tag:VLlkXiRp+Zt8iLFl15yXDQ==,type:str]
    pgp:
        - created_at: "2022-06-25T09:36:55Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9MZu0oHqP6dARAAhltPD05ItYMaK7IEWrEroGACW+01LHXref8GuobUpBq2
            rF0bXVRmMUIhuK4tnChJko9HW/tACCYUxfA+Afk5jUpiQvB1lRh2FYSHmQcGgBPL
            abUW5Chonm+kQ6B/ygBM2liUdfKmIb1/TTM5FmEw2Te/LYRY0M+kIzSxFIkQasf8
            bVoU4OL4y0QL2aAK95a2+cAv6ZjVGGwNqK5u1PaS2+zQAvittIzB17ACMx0pgeTS
            2GIjJ2ZYVb3RyzGY4q8GQDHnO9xmrd9fk9keSlDi0rt/83mB+tWsuVzcFgrM/9x0
            CzFyCOvMyfl/eHyt0FkxAScleVAzWEkMNAex4SilRmUfWfzq7ZvAZlZlzuE7hy4+
            PUkO5NFeusQUwDcigzBANrxEr3xVs5MxxZcU+JVAtSQR1XlQ8vQn+vRuX+TNXomI
            CYuXKi1VEjhfWCwH8EVHwXkC76SxWzNOsfLSuMeDL2Tv6dNiEag7VUfrqnXw5yBX
            esPGyCXLYXuPUjY2Ekcl562aXeuHLcvOYKbB2o6XNfTpCkEzi64heeElhIHOmT3l
            X9oplKwKpJiC3mvVDteV80dHcAahKkaG3pm13T7pyb0SAVOlrOjC+X3hE9I3X9Vo
            Rz9BbWYthWX7RLxsM/9GeoVGgDBmyLcsrEtTmIKEld6lggY7OHUj1tFXHDOhG8XS
            XgFRU6fa2qM0qXg58YK+qcp+GH6bXntHoAKaPGGkcwhcIYHSGOxnMA41vIP6E0pd
            p8y1y3RYAJd+SLWNhUkfWpx4BLGC2PsyMEIdEkfqaoFEqq40cITdT6KWzMSdp88=
            =jgXZ
            -----END PGP MESSAGE-----
          fp: EC621778D7E4AD9330404D6A6A00CDA35DF9B2BC
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
