apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee2mqtt-data
  namespace: home
spec:
  volumeName: pv-zigbee2mqtt
  storageClassName: "nfs-zigbee2mqtt-data"
  accessModes: 
  - ReadWriteOnce
  resources:
     requests: 
      storage: 128Mi
  selector: 
    matchLabels: 
     usage: homer