---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: zigbee2mqtt
      version: 9.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values: 
      image:
        repository: koenkk/zigbee2mqtt
        tag: 1.23.0
        pullPolicy: IfNotPresent
      env:
        ZIGBEE2MQTT_DATA: /data
        TZ: "Europe/Berlin"
      service:
        main:
          ports:
            http:
              port: 8080
      ingress:
        main:
          enabled: true
          ingressClassName: "traefik"
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
            traefik.ingress.kubernetes.io/router.tls.certresolver: leresolver
          hosts:
            - host: "zigbee.${SECRET_DOMAIN}"
              paths:
                - path: /
                  pathType: Prefix
          tls:
          - hosts:
              - "zigbee.${SECRET_DOMAIN}"
      resources:
        requests:
          memory: 100Mi
          cpu: 100m
        limits:
          memory: 500Mi
      securityContext:
        # -- (bool) Privileged securityContext may be required if USB controller is accessed directly through the host machine
        privileged: true
      persistence:
        data:
          enabled: true
          existingClaim: pvc-zigbee2mqtt-data
          mountPath: /data
        usb:
          enabled: true
          type: hostPath
          hostPath: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2486924-if00
      affinity: {}
      # -- zigbee2mqtt configuration settings.
      # This will be copied into the container's persistent storage at first run only.
      # Further configuration should be done in the application itself!
      # See [project documentation](https://www.zigbee2mqtt.io/information/configuration.html) for more information.
      # @default -- See values.yaml
      config:
        # These will be applied ONLY on first run
        # Home Assistant integration (MQTT discovery)
        homeassistant: true
        device_options:
          retain: true
        # allow new devices to join
        # WARNING: Disable this after all devices have been paired! (default: false)
        # Note: this will be controllable in the UI
        permit_join: false
        mqtt:
          base_topic: zigbee2mqtt
          server: "mqtt://mosquitto"
          include_device_information: true
        serial:
         port: /dev/ttyACM0
        advanced:
          network_key: GENERATE
          log_output:
            - console
          log_level: info
          last_seen: 'ISO_8601'
          homeassistant_discovery_topic: 'homeassistant'
          homeassistant_status_topic: 'homeassistant/status'
        frontend:
          port: 8080
        experimental:
          new_api: true
