---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: zigbee2mqtt
      version: 9.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values: 
      image:
        repository: koenkk/zigbee2mqtt
        tag: 1.23.0
        pullPolicy: IfNotPresent
      env:
        ZIGBEE2MQTT_DATA: /data
        TZ: "Europe/Berlin"
      service:
        main:
          ports:
            http:
              port: 8080
      ingress:
        main:
          enabled: true
          ingressClassName: "traefik"
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
            traefik.ingress.kubernetes.io/router.tls.certresolver: leresolver
          hosts:
            - host: "zigbee.${SECRET_DOMAIN}"
              paths:
                - path: /
                  pathType: Prefix
          tls:
          - hosts:
              - "zigbee.${SECRET_DOMAIN}"
      resources:
        requests:
          memory: 100Mi
          cpu: 100m
        limits:
          memory: 500Mi
      securityContext:
        privileged: true
      persistence:
        data:
          enabled: true
          existingClaim: pvc-zigbee2mqtt-data
          mountPath: /data
        usb:
          enabled: true
          type: hostPath
          hostPath: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2486924-if00
          hostPathType: CharDevice
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - {key: "feature.node.kubernetes.io/usb-02_1cf1_0030.present", operator: In, values: ["true"]}
      config:
        homeassistant: true
        device_options:
          retain: true
        permit_join: false
        mqtt:
          base_topic: zigbee2mqtt
          server: "mqtt://mosquitto"
          include_device_information: true
        serial:
         port: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2486924-if00
        advanced:
          network_key: GENERATE
          pan_id: GENERATE
          log_output:
            - console
        frontend:
          port: 8080
