apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-adguard-work
  labels:
    usage: adguard-work
  namespace: adguard
spec:
  capacity:
    storage: 1024Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-adguard-work
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    path: /volume1/kubernetes/adguard/work
    server: "${NFS_SERVER}"
