---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: &app synology
  namespace: networking
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-ssl-protocols: "TLSv1.3 TLSv1.2"
spec:
  ingressClassName: nginx
  rules:
    - host: &host "synology.${SECRET_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: *app
                port:
                  number: 5001
  tls:
    - hosts:
        - *host