---
apiVersion: v1
kind: Service
metadata:
  name: &app synology
  namespace: networking
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  type: ExternalName
  externalName: 192.168.178.35
  ports:
    - name: http
      port: 5001
      protocol: TCP