apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mosquitto-config 
  labels:
    usage: mosquitto
  namespace: home
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-mosquitto-config
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /volume1/kubernetes/mosquitto/config
    server: "${NFS_SERVER}"
