# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: code-server
    namespace: home
stringData: ENC[AES256_GCM,data:pxymwZcWuocybquvknnvh3oY3sMdIhDdeN11SCHu8Dpf6TQOVQwIroefMbM7uZuQYY6syJHi5Dz97XviF4jncWVA/2OfCiZvSpLoTyRTiXQ05ubyxXmsvSjSENsjb9e/+n4L7eGQo8CdH9Zw0j2KXKLyONJp11nDR3Xz1qmBaVyDwEOiYQCqJP9/zjSAi3k/qzz56r4WvdVNmT21fMhdSAVPIOgUqLllUjMikjFRFdYUVo/DNdwu1wtF99FMw7Cjsb4sEC61VCtX144Ot1IJDy9A20tYtOmUHjLLjFu6zRvfLxzm58CBsKD4NqvYROewFqz0MoOUVcpsktUsX7kM3eE/J2wzcIugJpiR/jzGUCM2xheaAY4biCdMTzf9ebqjkfsq9DSAYIP4dckennPwS3bJlp6iNV9GOulPI6R1YrfCUM3VDz2vNxIY+CJF726FOQDpkQY34oelS611nQCjYcYmdvBrk99HW0D0QwOfIznf2MEXnhr1nzT3dPaVH+4HHC6djrCJnUTCYGaz11KG50iWEml5KeCevgouLQ6QbTnQmY/kKquBQwu5VwZmmUqvAM5sGKnIE/+P+JKZUZxwOpegR4DyjxZLjRvCwlOZwarQZZ2zB219+DQKNXVMmJsxqT1JXPTC46tK2mNb0e0+EdGZTZC4N+YGaCqMtw8/Uz/bPZqnbeNcTYAmvE3X7/ysHANFE/sD1ry2pfjDYwxUlQofUWFPfa+mxrrtMi/qgiaeheOhkxu+mxEoZAijH2OvBX9l3AP2t0Ix8Auv+eq9W9StYL5+PNp8rrCitwsX6l9SUvmfcTni/VtefySkxg3zGcjBhh3nw+TrQ2UjwpgHLa2viDlvdPXDRDe8eijSbKGpUlOD92zjboJ6MOUgowS53/vK8HQYNARwIvDdFTRZppJnCKaBURKQHbhgAsgMFrKQV5Dce/QTUtxFwkCNXIHfVGT476qff+Qacx0UAP8UucxYiX5Atg==,iv:INbBxAT7ZYkfRdP7dWJgtLYk+M/pwy7j2zvMcIwkIXI=,tag:UfrMWaArwvZo4AphyiTmig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-19T16:33:48Z"
    mac: ENC[AES256_GCM,data:pj0bpTDLEZ3uvjL9WX10gpH8osMnPQJ9P45sLtD84mqvMQ64cyKGuse7XrYrQUbW8o4oakjVMNXDkjsG+HU6Xw097RHV18/UfvSdt7lMonbD/U7lK52OaaadiE0fWLyDpz+1wZkOJ9ajqF/1P75B2sXMh0QaEa0R1nUOIBC8upQ=,iv:gXXQP5NXeNN3TCu5Th3odBUI90kRBr5azbd0OYf6Xb8=,tag:WrN+xuW9S9m3rvYQPjhkYw==,type:str]
    pgp:
        - created_at: "2022-02-19T16:33:48Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9MZu0oHqP6dARAAnrWGme0qr82mcfWiADt6yDVOC8KMVqisCn0Z4QwQiFgP
            VtV80uAmUbCYAcPs+RHjdQ0DaZo7x00xe8fcDBY/yZrSfgCVYzrn7zLMmOc6eBJJ
            SMC5FSmf6BW9TkqTOyhoUNnIANPMDzl4z/g8YT0Cz/4VH5JYI3I18B0z1RhdsiLG
            QpmAKF5P0ezN/TbVQwnp8g4Cm6mKSa/imcl5zqugAFkQYSSye4CWP/vUZw7eLnAl
            W0m/Y3iM2FCGmbeT+YRtFuzK9Y1mHVQP2kbPAz7tbdZTI0bngPbKG6up/0io9z8f
            0ukxXc7HMO55wyzYNcFGCN9G1lapINizqqdyrhRf4MWgJEhY9qTl+IgCch4NP0MX
            AV0Kq1FKzpgvkQQUSujHJ6nX9PH9ADaGclunxWSku/xpehXzvsnlxK5ICislLdIO
            rOMIUjOxPVFtphHR6p6raIYe6qxBJVUPITMgSj/I6gJsbKkVuo0kZ2f4CBFr7n4m
            08VlT+L1ixGGV9L0d3r1dX2R7mtoKGsuxB3oIt5PBMw67ALlwKgSOCxUZ3Qf7aDl
            +x1Q9g5xfk9q6p/APLJXaOureRayprT003Ocxxc7N+OgF6GuySQuhSsx4yDchNyE
            zM1PS/3350/Br4oT8niaL5xbaDFl8e/PKwgdOu9wfZqW71p7JkA6kxp4RSxQ3yPS
            XgGJ+DUjCCCkBmCxqUQhsQYzZwnDQ0sVXnZ3XQ3EFDIidnwB67bTSOtbKOn8muuy
            t0jemLBjjQT4WFoXRI0Gbcqt089r6MehedQJgFAOmSWDlOslNu6PgS96UjBXc1g=
            =eIeR
            -----END PGP MESSAGE-----
          fp: EC621778D7E4AD9330404D6A6A00CDA35DF9B2BC
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
