# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: code-server
    namespace: home
stringData: ENC[AES256_GCM,data:xEH6CX4L6Thbqaby9LERaXbgdmE/ZJn3lPCYIba2dE+U32ZLLySISN+1IESKoADl0hjrqWxpSrPW8e8xM8Yx1+My+sPNpxE75DQ2IqkMmpdis+H6IHgI6/3xcaQYrf4DRelYlfeLqfbFvvWITjGos+ClQBZMNYyGYYMawrO2650AltbX+H2XNWpmCPct5qLRtgWfJF/Gupg5637ahWgErnAIVS0c8ui8C7MIfSzTuN2NKb50nbQcLEWyJnJXhPw6Kjqn18kLIpYf7GnUvGmof7GyCMUPEVNR8vfI14N2/PTPASp63Ja4YNNhZT78RuWAtez43OyU5auRBZKInFaPrhxm3bjSsbHRFO7hSh5w4iu6Fzy6wV8EyEo/weBqyjiD8PAewaA9DmZrt1AaKFz/KjjtzWFDhvceguJsO5DJpqtMZjDMArYVU7JqZi0HcCaCBvnLWxvg4dQstsXGDOY4j3IucyT1kmEETDqVROpTGkyhzQXI/Y/nVINEzcy8w8Sw0Q4CkqEqL33rf0UjUrjgCL4XU3Xgws3ov8shEdFkrY6cMWIgHObqYIbW1APyiivLJxXEZrlPZuAyFakz1fFwhV9ntZF9ksHOksUplWsEOjk5JQ+yZkgq9NJxAw31BKGhZlHEt8c3wCkT4MHtH2/W6p/DlyISSl7dPdWCgCZ4SKb7W74oltn63sID8kP/3VT6jHNW5lCHnDCWC/7V6KCpeqybPhcCQ8UG1d7bLAvfWq5g5CYTKhEUzjRL4rviXYmzwj2L9ysIPsDSlOWOjiBmjipq03eqxszNZbrsKC/eXeLipnMJ4VMxSw7HMzzruDSgOTGgVlt4bQDD/rbFojV12FCsdE8ztSBo6Eo/wHgxXSQdVvOHZis223kGFwAjKY80Ie5HpRr7UMOHNfdLgnf0TTdvdn/zDyPSIvwYGcMMb3aDMT8nU5eOVNnKXM3hsN688Gn72cB00kcSzvL5Wid3bLDEnEB91g==,iv:D6kIeTNgwl2wi5B+f30Zaar5ARSTUzBN8h5yI3fb3mw=,tag:W0Fm7eRoHkPv+/WLli3pxg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-19T16:40:07Z"
    mac: ENC[AES256_GCM,data:lt6E5sYtzDwnZQQSWSf1HsW80AQsclH/kEx9Kdc+1Mbs7bq99aUH4eCdI1uUK708W8PVZZP6WhZDd6XDG1INPZ8pqoltAyqoWOBHU2aVLSbgRIRiwXYqshR9daG+busD2ZzXj1koYribw8QCOeuAaLcQ+5Wj2jcKgY+ASCoQySs=,iv:XACh9uQ3AHHcQQO4z22u3oQQpCIHjW+qtwfmTaQgTWs=,tag:8sx+LnNgDobmwW17amnyNw==,type:str]
    pgp:
        - created_at: "2022-02-19T16:40:07Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9MZu0oHqP6dARAAoK08kzkdNAEcIqX+t573m3hY2OxaBaQ/u9Po33YYSevL
            Po7jyJvgi+l+uZ2Mp313jNvHKJGw7xb9z+ETOlJKY5Gfdy2k45L8hpDKg4o7xr3Z
            6s/lS9LfmgZ1qNmcAWGBn+dkBb7k6CYi290hl/VqqVjWHW16FLHlGCD72Bp8EnPI
            B+d+Kos1nst/8K2QVrvNuMAe/qJjZXG/GGfY3j3GE+E/CScw69IjxlRdrrbIIHfn
            OJnprEW7ab81Ip2a6EfxxKfzVUhXW8fKqf6K0wJWc8nNawuV0tiX7bVL9hAZ6iRf
            M0jUoWIYMCXdLL+oYsq70pJah9aZka18zzmfjIa7GS77vC1eJcnAVyuKuIVUI/X6
            RJogdu7re26gHAv5bkvSDLz2ZMt5tShBDlL/cxkZzYOaxBs6gj5Ypxr0e1XBdcZh
            xZJmcTfmmKbTrJa6yJ5IycKjhnZWv7XUmCc0F735QG/qhSxmsg+pfwvft3+nabNF
            KImYpu3krhGzfRPW6iMNEyuloTmMVDQY2TJjdOf1FZZOY7k057sfXwEXVyZzSWDT
            n6z+mt7k43c7kl8tHZVcUiya4U+QfRvO143McFfXrdPtp06YOGQA7HPUHxS0uh/M
            Gxuv3JxSo0x/os2U+rTb0MMCl9zDDb9CUYNE2i4SZTTk/RDtaayPHXVKBVdnPXXS
            XgF1vl52FgypzBFUa3vooePixRZmPf14oEvaYIC6qYhg0xd4Gk11yZUO8SkMRD3L
            9Li0rcUgAfbXCkDXZjuTZA4H/zaSasSCI5+1E0oWXCUJVZMnSjZalb/RHK1T3zg=
            =XzRa
            -----END PGP MESSAGE-----
          fp: EC621778D7E4AD9330404D6A6A00CDA35DF9B2BC
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
