apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config
  namespace: home
spec:
  storageClassName: "nfs-home-assistant-config" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: pv-home-assistant-config
  accessModes: 
  - ReadWriteOnce
  resources:
     requests: 
      storage: 10240Mi
  selector: 
    matchLabels: 
     usage: home-assistant-config 