---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 13.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2022.7.7
      pullPolicy: IfNotPresent
    env:
      TZ: "Europe/Berlin"
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "${SVC_HASS_IP}"
       # externalTrafficPolicy: Local
 #       ports:
 #         http:
 #           port: 8123

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: "hass.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
        - hosts:
            - "hass.${SECRET_DOMAIN}"

    securityContext:
      # -- (bool) Privileged securityContext may be required if USB devics are accessed directly through the host machine
      privileged:  false
    addons:
      codeserver:
        enabled: true
        image:
          repository: ghcr.io/k8s-at-home/code-server
          tag: v4.5.1
        env:
          TZ: "${TIMEZONE}"
        git:
          deployKeySecret: code-server
        workingDir: "/config"
        args:
          - --auth
          - "none"
          - --user-data-dir
          - "/config/.vscode"
          - --extensions-dir
          - "/config/.vscode"
        ingress:
          enabled: true
          ingressClassName: "nginx"
          hosts:
            - host: "hass-config.${SECRET_DOMAIN}"
              annotations:
                cert.manager.io/cluster-issuer: "letsencrypt-production"
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - "hass-config.${SECRET_DOMAIN}"
        volumeMounts:
          - name: config
            mountPath: /config
    resources:
      requests:
        cpu: 100m
        memory: 400Mi
      limits:
        memory: 4000Mi
    prometheus:
      serviceMonitor:
        enabled: true
        portName: http
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config
  
