# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:2QSrpePVf9csdA5J+CBah+3N4+UBrX2Y+m9QBseweK4qLhful5y2fw==,iv:btAgWGecGDvulMuAdDf8D2V6tM7oShXLSM3o60MK1mg=,tag:cgwjymkaK6HVTTpOL0oJAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-05-28T10:38:41Z"
    mac: ENC[AES256_GCM,data:kXyhaEExIptvItf7LJfUQrGVyZYxukIbbIdsP0IQqqx/5aUl0Xoa36Jsr5MTGP+8NizAuHKHP1hLpBXBAtq9dfruW9gYGN2cjL+PlDtaQSFrwPcJq222jyxfbtVbvwogmJtRv2Syd3grScBfgQ7lN34L5UbJ9gfb0GJkW0PjFZU=,iv:7fofI3t6GhfXJ/PYdtMfgG57+VNd77t+X3EycdP7Lpk=,tag:OfaL/sEtABflrl1igk6Rhg==,type:str]
    pgp:
        - created_at: "2022-05-28T10:38:41Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9MZu0oHqP6dAQ//ejH6ZpE6QzEqA6xvGCKp4r23bqkOFBDbV3gGaRq/6pIJ
            iybtAQgWUJLlZu4RdhUyxGwCM33gNQdQF1h5/j6Bv/BB50mzZkPaQ8aIjfpY2vJY
            Ms2Bk3celWK0VjtMycvTZbGTBh9mrS0RkqdF/fKGekdw8YBDPFQDLvxzZ4R+98qX
            aIWTkjuRlUdlpLIf9PAZ2QADdaPJvk4neu/YpP/N+0MFtp6H8qJmusQG6wrJ5tz/
            9l72yoj9ml0aKTXhlz32ngG2/396XXfnAXGhpRc3B61WUqOES+P/nZ96K4caofHi
            7ttNZJgFdbXlv+GOAeeGXe24ANov3OPLOq4eiMP7I+JZaYopV49XkFY52Xli2wnG
            98Q1C/70/td/S3vs7DR2ByI9VPgUFgvmeTlJSW695J5hDK1vsvPXT2ZLIbr7bSyv
            vgGL3wu2uNbz7axDatIj2MG1MmFkYSpFSjm7Qr0ArJMMn4gYRise5YaZr89xbvsz
            hDx6bnD8A27clF9X5seBil/Lx/lk2kk7wUWDPp3tm6c9FdLZxWSBQF13KrEd+0F5
            +Crc4KVATbNtw8GxxFyBsz5IMFL7u7wKaj2p1Va2KxjsUGm0QH7OAE6mzZ6PMk4h
            S9L45++5Rga0Tvi58vd8OFOansgw9VpzFEC1AesOwh/cxlQoyyA0qlWu7dU7F+nS
            XgF+/sTweJQJd45CS858sjSogRf85R5n9Mh/Bb4PIT089oBPopA8EcYCjU7aBvSQ
            1su4r1Qa/OwkULAAtN+mVZelbH6ojTKjh/FjReEfoUCtvNd8Q0lQU+/mIq5KWRk=
            =JhEQ
            -----END PGP MESSAGE-----
          fp: EC621778D7E4AD9330404D6A6A00CDA35DF9B2BC
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
