---
    - name: turn off swap - {{ ansible_distribution }}
      shell: swapoff -a
    - name: packages | remove crufty packages
      block:
      - name: packages | remove crufty packages | gather install packages
        ansible.builtin.package_facts:
          manager: auto
        when:
        - "'snapd' in packages.apt_remove"
      - name: packages | remove crufty packages | check if snap is installed
        ansible.builtin.debug:
          msg: "snapd is installed"
        register: snapd_check
        when:
        - "'snapd' in packages.apt_remove"
        - "'snapd' in ansible_facts.packages"
      - name: packages | remove crufty packages | remove snap packages

        ansible.builtin.command: snap remove {{ item }}
        loop:
        - lxd
        - core18
        - snapd
        when:
        - "'snapd' in packages.apt_remove"
        - "'snapd' in ansible_facts.packages"
        - snapd_check.failed is defined
      - name: packages | remove crufty packages | remove packages

        ansible.builtin.apt:
          name: "{{ packages.apt_remove }}"
          state: absent
          autoremove: true
      - name: packages | remove crufty packages | remove crufty files

        ansible.builtin.file:
          state: absent
          path: "{{ item }}"
        loop:
        - "/home/{{ ansible_user }}/.snap"
        - "/snap"
        - "/var/snap"
        - "/var/lib/snapd"
        - "/var/cache/snapd"
        - "/usr/lib/snapd"
        - "/etc/cloud"
        - "/var/lib/cloud"
        when:
        - "'snapd' in packages.apt_remove"
        - "'cloud-init' in packages.apt_remove"
      when:
      - packages.apt_remove is defined
      - packages.apt_remove is iterable
      - packages.apt_remove | length > 0
