---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: cilium-charts
  namespace: kube-system
spec:
  interval: 30m
  url: https://github.com/cilium/charts
  timeout: 2m