---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: minio-charts
  namespace: flux-system
spec:
  interval: 15m
  url: https://github.com/minio/operator
  timeout: 3m