  apt_remove:
  - apport
  - bcache-tools
  - btrfs-progs
  - byobu
  - friendly-recovery
  - fwupd
  - landscape-common
  - lxd-agent-loader
  - ntfs-3g
  - open-vm-tools
  - plymouth
  - plymouth-theme-ubuntu-text
  - popularity-contest
  - snapd
  - sosreport
  - tmux
  - ubuntu-advantage-tools
  - ufw
