---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: external-dns
      version: 1.10.1
      sourceRef:
        kind: HelmRepository
        name: external-dns-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
  values:
    interval: 15m
    logLevel: debug
    provider: rfc2136
    policy: sync
    sources:
      - ingress
    txtPrefix: "k8s."
    txtOwnerId: "default"
    resources:
      requests:
        memory: 100Mi
        cpu: 25m
      limits:
        memory: 250Mi
    extraArgs:
        - --rfc2136-host=${SECRET_DNS}
        - --rfc2136-port=53
        - --rfc2136-zone=${SECRET_DOMAIN}
        - --rfc2136-tsig-secret=${SECRET_DNS_SECRET}
        - --rfc2136-tsig-secret-alg=hmac-sha256
        - --rfc2136-tsig-keyname=${SECRET_DNS_KEY}
        - --rfc2136-tsig-axfr
        - --source=ingress
        - --domain-filter=${SECRET_DOMAIN}