---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.cilium.io/
      chart: cilium
      version: 1.11.1
      sourceRef:
        kind: HelmRepository
        name: cilium-charts
        namespace: flux-system
      interval: 5m
  values:
  #  cluster:
  #    name: homecluster
  #    id: 1
    rollOutCiliumPods: true
    localRedirectPolicy: true
    kubeProxyReplacement: "strict"
    #kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
    nativeRoutingCIDR: 10.10.0.0/16
    k8sServiceHost: "${CLUSTER_API_IP}"
    k8sServicePort: 6443
    loadBalancer:
      algorithm: "maglev"
      mode: "dsr"
    tunnel: "disabled"
    autoDirectNodeRoutes: true
    ipam:
      mode: "kubernetes"
    operator:
      rollOutPods: true
    containerRuntime:
      integration: containerd
    
