apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-uptime-kuma
  namespace: uptime-kuma
spec:
  volumeName: pv-uptime-kuma
  storageClassName: ""
  accessModes: 
  - ReadWriteOnce
  resources:
     requests: 
      storage: 4Gi
  selector: 
    matchLabels: 
     usage: uptime-kuma