---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: komga-data-nfs
spec:
  capacity:
    storage: 20000Mi
  accessModes:
    - ReadWriteMany
  storageClassName: komga-data-nfs
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${NFS_SERVER}"
    path: /volume1/kubernetes/komga/data
  mountOptions:
    - nfsvers=4.1
    - nconnect=8
    - hard
    - noatime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: komga-data-nfs
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: komga-data-nfs
  resources:
    requests:
      storage: 20000Mi