apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prometheus
  labels:
    usage: prometheus
  namespace: monitoring
spec:
  capacity:
    storage: 20000Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-prometheus
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    path: /volume1/kubernetes/prometheus
    server: "${NFS_SERVER}"
