apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-prometheus
  namespace: monitoring
spec:
  volumeName: prometheus
  storageClassName: "nfs-prometheus"
  accessModes: 
  - ReadWriteOnce
  resources:
     requests: 
      storage: 20000Mi
  selector: 
    matchLabels: 
     usage: prometheus