apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-uptime-kuma
  labels:
    usage: uptime-kuma
  namespace: uptime-kuma
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    path: /volume1/kubernetes/uptime-kuma
    server: "${NFS_SERVER}"