---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-settings
data:
  TIMEZONE: "Europe/Berlin"
  METALLB_ARP_RANGE: "192.168.178.241-192.168.178.251"
  NGINX_LB_IP: "192.168.178.250"
  KUBEVIP_ADDRESS: "192.168.178.11"
 # CLUSTER_API_IP: "192.168.178.10"
  TRAFIK_LB_IP: "192.168.178.241"
  SVC_ADGUARD_IP: "192.168.178.242"
  SVC_HASS_IP: "192.168.178.243"
  SVC_MOSQUITTO_ADDR: "192.168.178.244"
  NFS_SERVER: "192.168.178.35"
  HOME_SERVER: "192.168.178.10"
  CLUSTER_ID: "0"
  CLUSTER_NAME: "home"
  NETWORK_K8S_POD_CIDR: "10.43.0.0/16"
  #