apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:hrDO1ZvzQYBCscNT,iv:683udHBQxJwsL5fld0FGsqSnpWt2lcREALHZcwDH9NE=,tag:OrXCZl7mGp/ddwOACuB6Gw==,type:str]
    SECRET_PRIVATE_DOMAIN: ENC[AES256_GCM,data:KqxEXPUXS/Gx8c+M4QTn/37/u8xFn8zt,iv:GUiC4PzSeUdv8d9f4Vr9StmxkDsOaqKzv3j3x3dlH28=,tag:MGe7aGCc32m5zObPQZjwUg==,type:str]
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:OnhzYvbtqjw=,iv:6fWMlrZuhv9DqukqlKdPQv5R+rlGIcnZMfOOvK8xf7E=,tag:akoQUaQrLei7OV83pMCY4Q==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:RVt6djlxHd6CgDhIxs9LdblsTBgWqzVscLAu,iv:nKbFThO270J9KfmfaFdsvhTAuwOoGt8AHuwfnyfJm88=,tag:BiJFOt9bHcnTemHZGKuB6Q==,type:str]
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:BqivR17JuZIhXZSeTF8eqQydUnToDF+kxczWCFDRcCIHo2WE5qomvg==,iv:QEUvel80TOmuhPjX6ObyNxiit+5itTiURqZElq80MpY=,tag:mrdPro8AtL0qZ1a70kqBxQ==,type:str]
    PROM_LOGIN_PW: ENC[AES256_GCM,data:L9M3bZiP9GiphnIkbmHeT1YcT08rXiOaJ7M=,iv:wcDSM8jt1qun+BH1qaAO566yerapJh9Kmx13tqcuo1w=,tag:OZ+kSl03gN5ux3RVgKM9AA==,type:str]
    SECRET_MQTT_USERNAME: ENC[AES256_GCM,data:EGVPOLjuE/ih,iv:kz2KMcwt8Hb1ACQTh1yEHuoQQx89btmc2vfBFoAbeJQ=,tag:E+fIX6G68m74DFXrdxnalg==,type:str]
    SECRET_MQTT_PASSWORD: ENC[AES256_GCM,data:eAoa4isidIOcegptSzy8Ik7Qk2NLQAU=,iv:/5A/0a4hcsthb6zTuaaD2dcupHipTbinxizdD331oDw=,tag:48PcVjdU4e+bF6HPHqwohQ==,type:str]
    SECRET_DNS: ENC[AES256_GCM,data:UdafeVcCpPYw1hMODQ==,iv:SbLZron6OuqbKvisKTuK4HRJc0YB9y4A24J6azhcaJc=,tag:+71UVX6/WQwFo67RcePNtA==,type:str]
    SECRET_DNS_KEY: ENC[AES256_GCM,data:P1jNZzt2+dQhRPkdQHJE,iv:fDCgS73rSyzNbDkIQptSx+XY4bAiup8cJQj7L42LsdA=,tag:q+DNuWOVC1FT8l9JPosHew==,type:str]
    SECRET_DNS_SECRET: ENC[AES256_GCM,data:8SJN2OX/4A1/Vhw4ir72KVpD3+shB+Z6b+cSD/LEZpd3CJMOTNgzu8HFS94=,iv:fzfCOZi8n7XbMtrxIV9MrGeChnS8t6jenee3esi9ECg=,tag:K3S4vgTo+OVl3JOxJqUAAg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-05-28T10:38:00Z"
    mac: ENC[AES256_GCM,data:D7vZ0mYVmBIf3x0yeNYhxy8a++m0qWCMzOnUCsUqRuynnt61f9VrpjiNHSYYUzCcehrBirbJ2awOv1V8k2VnvCTtDZF3WkL/a6lW6uLnHasZoS8CqUnzLYDY1l53w5UdJkeBcO+gWIIalIV7ROcXPgQByqx7vWAKX9Tt2z0S9HI=,iv:0D5shIu06CIJ+mqqmE8kEh0RNcGPsgXQ9A0YbWmu7/M=,tag:ranBK+UIEGqUvG91eg5jjw==,type:str]
    pgp:
        - created_at: "2022-05-28T10:37:59Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9MZu0oHqP6dAQ//dAYJmCyYT/ssPGiZRKzr6/n8jWcQzIDXxOk25eKRYP71
            CrGOVTSmsQC3dr6iZS8JcXgPutnJ2e48O3gxNtJXSS/0ls8V32HPZt0byq4MnqI5
            dk+F085WdptyEniT9YOnzceFx48cZiXrvA0H0yAlMf6JWp0OjQIwN1QYqoTkGm2f
            F8b7HhEmELgv+QD5uBYwO7XQbbdSF1Keacc1nk4GPFntY2mz/kogb7IfQYnJGnLT
            yqc1Am/VdELO31j0B3Gdrt4tLFZvhbKAexaF+ZM++88H/YaVsXEr3VWeFBs7s7yL
            dMokvTD5C0G3Yw2aVHzdi/LrQ+YFDkUrowg24XW6rutIIJ74Yojs1zRYCQ4vpdLy
            6YDQNOJ0SGy9BPUghbppovqhGF40LVDzLdJjZNccsLFe8Rijqws1uVG6Q3XzvfOY
            L0/dXSurYuToU8aiNtdmsDZJafhBwQtZ1LJjp9ZGcXawFjnwA1P7Hv8ny/ToUYk8
            znN3467S/RAJGFevdmiGVICAXr44AQDU+t8hTEfEpWo2GxkL8QPwglyqI5CNTSRZ
            mYfAkrWFuoB3OdMghqCP3PhHe5AxGyNgIexuu8Jo72pV9cB1gAqxTma08wYrgJzv
            SiRAD0nb3PpkPpZsnGXXQ/BH1Hgk5yrgGWpC4gcZ9ShThAnXmIBjOVggZpith0/S
            XgFK9By/z4lJ04gfh1Tq/b7HkWvHomk2x3COF6KaWJytOtoFrPJj0XfYGIZm6dmi
            jnAkrgSpOc0T1eK+bX4H1TLqOhoo41M7B892i7rPx5nU55a7llwiRYL2B39oiJM=
            =1+Me
            -----END PGP MESSAGE-----
          fp: EC621778D7E4AD9330404D6A6A00CDA35DF9B2BC
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
