apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:1nYPC7yi9+e2zWuc,iv:qRwKSbkLMu8sbzFoFAm6E7wCxaIo6YZx92Phet5CUKY=,tag:OgPjKabauP0npy189tnc2g==,type:str]
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:aegiijueBkwtZiLn+6/xODmqBNeio9Yr9z89F2dIFSyyx9xHveHayA==,iv:jedePa70VPTP6OxkK2WF3BO+78u2vV/Tc6rl79p0HS4=,tag:nJhp9OuKEmq+TNbutDwIfg==,type:str]
    PROM_LOGIN_PW: ENC[AES256_GCM,data:lzqkx2qJ5dhAMiUnCmLjtT+jwi2g+btx6Sc=,iv:1AYOq2zB2FioDHtpIIGPWfmRkpx6uRjZ1glzRdRPANM=,tag:4C0nBqJfMOZuhVhznOQm/A==,type:str]
    SECRET_MQTT_USERNAME: ENC[AES256_GCM,data:9+wp1I5vVgYs,iv:N4nNpNwgERlzGUB34hVu1wzPToEgeg8UR3i/fLKHvbY=,tag:Xy5M322pnVhUMrtDRbG4ow==,type:str]
    SECRET_MQTT_PASSWORD: ENC[AES256_GCM,data:8izIy2I7y3IF2CeE3k5onwSrGYTnD3U=,iv:Pa8BbaYQjlLMpBF/nepMd02cZJuf0K2d/oziVpPRp0Y=,tag:KnWErT6kaBe2eNELaRA7yw==,type:str]
    SECRET_DNS: ENC[AES256_GCM,data:Nvw6eT5w4JM6AbwwXw==,iv:XQWU2i1/0+hK2x8pzBdpzgVbD0wX7wRiSnQf46wDIDQ=,tag:OFZp2vJsprX/O9pDnizBnw==,type:str]
    SECRET_DNS_KEY: ENC[AES256_GCM,data:6GlY2J5pvbDqF3AqvmS9,iv:5+9X0NPDTDqF5Vybi9kUZGoqgkkEkZpuNUBDKgWYG0Q=,tag:RQg1NwuYoT/TqFUvCboFzw==,type:str]
    SECRET_DNS_SECRET: ENC[AES256_GCM,data:Ukrz/2uelLu7POtndZt0K7YXbJKeAPj3X+XdTOL1usFGjolAp9BvAnArutI=,iv:2x5OMRbgqhd45fJhlvg+YOgDt3P/YewLcSAPEeJzqT4=,tag:Kse6sskpmvWjmLus3uZ6KQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-05-23T20:55:24Z"
    mac: ENC[AES256_GCM,data:y7HiMVmNZa9ULUFN5eBjMiZ79q2bicFKP+t/kUSKNIddI+dmD8Son/7lkbLL5LaUcoG7CzrYwJtJ7DT+3NqfVAnODOrcMTh2YloAV2MwTtnaXejYDGm0Xg792JS+BgZbeLDVRa+oIFG6u3bwdcsKJUdoz1WGrw+gffpKyCrUDhE=,iv:dlVF83HvpeWaeJfLKeZaE+WyMU9mWPSwrZpZh7ROU88=,tag:Q7ilVg4XwVUR7H7hCy8voA==,type:str]
    pgp:
        - created_at: "2022-05-23T20:55:23Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9MZu0oHqP6dAQ//VYm3FidTzFPuBP21Q4hTbLqQ+xERJlbxLyoKTDZ41JPE
            ag9UIG2JqBpv4LYVwKKlBLPav/LyIGApU8xOYzqqXV1NbhLJAc0gvIHQLfxioI4J
            MK3GCcMsHEAFyVUFsKsg0OrciSd+xvxWTx/kkhdISQ/JMEDy9f6OlZWraYSNQ89a
            mF0eaZgoPxLQUZ1Cu+CrLp41ilaJfD01x+QDLth09+e+xaJixacFeRabid/XDLlX
            QwJ6up0fL4QzUVlHoQljGNc+0JexORX/EvVWIAUYZ00R6uiKp/yeXArIhkD5ZqkT
            aCuc1KgtV3k8dfVNx3BS9y8yLGpFK+kZOKJzfaRq2mt/sdwEKKix+dzkfeM5GjNV
            MCnY5i09WiWu/VAM8yR5MH32hMsRUx4PjUimkdUbnK0utDIM26mLMkD/keJ6Z8JK
            T/D9r5L7YT7utksqeN8hKJmZe9C9lLp1lF4MzvNYlfg84OopmbthGHCSYPe4WzFD
            W+GGeN//oId6MGwY/3o3tLfUdCcdiZVfkbKFPK3iot2z7QLMq7UwK6s3gyDpdAR0
            81Qi4kHPQfgxiw/bgphzKn2McsTEjdD25r1S6+E93uIeJf9N2bICA30Mpn8xUOzz
            6HE7e/HGOCLEvwyKtwI7cYtheOQ9FdhZ50ZeHcamPzm3wnyg2HPaFoUoIA/frLvS
            XgGZkMBDR5w4Wwwdb55/gPd+MbL1Kd24iRXx6CrH/owU0EtdIH0gHCucTtIyImYi
            JBbIvHvpcb6sCWmm+NOnK0aV7J+BTZS05bvXkMnmEP3HMyqgHY5XtAbs/UwgrFw=
            =gpfx
            -----END PGP MESSAGE-----
          fp: EC621778D7E4AD9330404D6A6A00CDA35DF9B2BC
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
