---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-settings
data:
  METALLB_ARP_RANGE: "192.168.178.241-192.168.178.251"
  TRAFIK_LB_IP: "192.168.168.241"
  NFS_SERVER: "192.168.178.35"
  #