---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-settings
data:
  METALLB_ARP_RANGE: "192.168.178.241-192.168.178.251"
  CLUSTER_API_IP: "192.168.168.10"
  TRAFIK_LB_IP: "192.168.168.241"
  SVC_ADGUARD_IP: "192.168.178.242"
  NFS_SERVER: "192.168.178.35"
  #