---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: crds
  namespace: flux-system
spec:
  interval: 15m0s
  path: ./cluster/crds
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
