---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  releaseName: longhorn
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
      interval: 5m
  values:
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 2
      reclaimPolicy: Retain
    defaultSettings:
      backupstorePollInterval: 300
      backupTarget: nfs://${NFS_SERVER}:/volume1/kubernetes/LonghornBackup
      createDefaultDiskLabeledNodes: true
      defaultDataLocality: best-effort
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      concurrentAutomaticEngineUpgradePerNodeLimit: 2
      storageMinimalAvailablePercentage: 20
      storageOverProvisioningPercentage: 200
      defaultReplicaCount: 2
      defaultLonghornStaticStorageClass: longhorn
      replicaSoftAntiAffinity: false
      allowVolumeCreationWithDegradedAvailability: false
    ingress:
      enabled: true
      host: "longhorn.${SECRET_DOMAIN}"
      path: /
      tls: true
      tlsSecret: longhorn
      annotations:
        coredns.io/hostname: "longhorn.${SECRET_DOMAIN}"
        cert-manager.io/cluster-issuer: letsencrypt-production
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        kubernetes.io/ingress.class: nginx
