apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pv-paperless-media.yaml
  - pvc-paperless-media.yaml
  - pv-paperless-data.yaml
  - pvc-paperless-data.yaml
  - pv-paperless-consume.yaml
  - pvc-paperless-consume.yaml
  - pv-paperless-export.yaml
  - pvc-paperless-export.yaml
  - helm-release.yaml

