apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # pv and pvc for paperless media dir
  - pv-paperless-media.yaml
  - pvc-paperless-media.yaml
    # pv and pvc for paperless data dir
  - pv-paperless-data.yaml
  - pvc-paperless-data.yaml
  # pv and pvc for paperless consume dir
  - pv-paperless-consume.yaml
  - pvc-paperless-consume.yaml
  # pv and pvc for paperless export dir
  - pv-paperless-export.yaml
  - pvc-paperless-export.yaml
  - helm-release.yaml

