apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-paperless-data
  labels:
    usage: paperless-data
  namespace: paperless
spec:
  capacity:
    storage: 1024Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  #storageClassName: nfs-paperless-data
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    path: /volume1/kubernetes/paperless/data
    server: "${NFS_SERVER}"
