apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-paperless-export
  labels:
    usage: paperless-export
  namespace: paperless
spec:
  capacity:
    storage: 1024Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-paperless-export
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    path: /volume1/kubernetes/paperless/export
    server: "${NFS_SERVER}"
