apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-paperless-export
  namespace: paperless
spec:
  volumeName: pv-paperless-export
  storageClassName: "nfs-paperless-export"
  accessModes: 
  - ReadWriteOnce
  resources:
     requests: 
      storage: 1024Mi
  selector: 
    matchLabels: 
     usage: paperless-export