apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-paperless-data
  namespace: paperless
spec:
  volumeName: pv-paperless-data
  storageClassName: ""
  accessModes: 
  - ReadWriteOnce
  resources:
     requests: 
      storage: 1024Mi
  selector: 
    matchLabels: 
     usage: paperless-data