apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-paperless-consume
  namespace: paperless
spec:
  volumeName: pv-paperless-consume
  #storageClassName: "nfs-paperless-consume"
  accessModes: 
  - ReadWriteOnce
  resources:
     requests: 
      storage: 1024Mi
  selector: 
    matchLabels: 
     usage: paperless-consume