---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik-ingress
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.traefik.io/traefik
      chart: traefik
      version: 10.4.0
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      name: traefik
      # defaults to appVersion
      tag: ""
      pullPolicy: IfNotPresent
    deployment:
      kind: Deployment
#### Nur eine Instanz Augrund der Let's Encrypt challange
      replicas: 1
    service:
      enabled: true
      type: LoadBalancer
      spec:
       loadBalancerIP: "192.168.178.241"
#        externalIPs:
#          - 192.168.178.241
    persistence:
      enabled: true
      name: data
    #  existingClaim: ""
      accessMode: ReadWriteMany
      size: 128Mi
      storageClass: "nfs-client"
      path: /data
      annotations: {}
    logs:
      general:
        format: json
        level: WARN
      access:
        enabled: true
        format: json
    pilot:
      enabled: false
    ingressClass:
      enabled: true
      isDefaultClass: true
      fallbackApiVersion: v1
    globalArguments:
      - "--api.insecure=true"
      - "--serverstransport.insecureskipverify=true"
      - "--providers.kubernetesingress.ingressclass=traefik"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.entryPoint=metrics"
    additionalArguments:
      - "--providers.kubernetesingress.ingressendpoint.ip=192.168.178.241"
      - "--certificatesresolvers.leresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.leresolver.acme.dnschallenge.provider=netcup"
      - "--certificatesresolvers.leresolver.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.leresolver.acme.email=alexander@breidenbach.koeln"
      - "--certificatesresolvers.leresolver.acme.storage=/data/acme.json"
      - "--certificatesresolvers.leresolver.acme.dnschallenge.delayBeforeCheck=900"
    env:
    - name: NETCUP_CUSTOMER_NUMBER
      valueFrom:
       secretKeyRef:
        name: traefik-secret
        key: NETCUP_CUSTOMER_NUMBER
    - name: NETCUP_API_KEY
      valueFrom:
       secretKeyRef:
        name: traefik-secret
        key: NETCUP_API_KEY
    - name: NETCUP_API_PASSWORD
      valueFrom:
       secretKeyRef:
        name: traefik-secret
        key: NETCUP_API_PASSWORD
    ports:
      traefik:
        expose: true
      web:
        redirectTo: websecure
      websecure:
        tls:
          enabled: true
      metrics:
        port: 8082
        expose: true
        exposedPort: 8082
    tlsOptions:
      default:
        minVersion: VersionTLS12
        maxVersion: VersionTLS13
        sniStrict: false
    experimental:
      plugins:
        enabled: true
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - traefik
              topologyKey: kubernetes.io/hostname
    resources:
      requests:
        memory: 100Mi
        cpu: 500m
      limits:
        memory: 500Mi
