---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: minio
      version: 11.7.15
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    extraEnvVars:
      - name: TZ
        value: "${TIMEZONE}"
      - name: MINIO_PROMETHEUS_URL
        value: http://kube-prometheus-stack-prometheus.monitoring:9090
      - name: MINIO_PROMETHEUS_JOB_ID
        value: minio
      - name: MINIO_UPDATE
        value: "off"
      - name: MINIO_BROWSER_REDIRECT_URL
        value: "https://minio.${SECRET_DOMAIN}"
      - name: MINIO_SERVER_URL
        value: "https://s3.${SECRET_DOMAIN}"
    auth:
      existingSecret: minio-creds
    ingress:
      enabled: true
      ingressClassname: "nginx"
      hostname: &consoleHost "minio.${SECRET_DOMAIN}"
      tls: true
      extraTls:
        - hosts:
            - *consoleHost
    apiIngress:
      enabled: true
      ingressClassname: "nginx"
      hostname: &apiHost "s3.${SECRET_DOMAIN}"
      tls: true
      extraTls:
        - hosts:
            - *apiHost
    podSecurityContext:
      enabled: true
      fsGroup: 100
    containerSecurityContext:
      enabled: true
      runAsUser: 568
      runAsNonRoot: true
    persistence:
      enabled: true
      existingClaim: minio-nfs
    prometheus:
      servicemonitor:
        enabled: true
