apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homer-config
  namespace: homer
spec:
  volumeName: pv-homer
  storageClassName: "nfs-homer-config"
  accessModes: 
  - ReadWriteOnce
  resources:
     requests: 
      storage: 128Mi
  selector: 
    matchLabels: 
     usage: homer