apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vaultwarden
  labels:
    usage: nfs-vaultwarden
  namespace: vaultwarden
spec:
  capacity:
    storage: 1024Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    path: /volume1/kubernetes/vaultwarden
    server: "${NFS_SERVER}"
