apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-vaultwarden
  namespace: vaultwarden
spec:
  storageClassName: "nfs-vaultwarden" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: pv-vaultwarden
  accessModes: 
  - ReadWriteOnce
  resources:
     requests: 
      storage: 1024Mi
  selector: 
    matchLabels: 
     usage: nfs-vaultwarden