---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  interval: 5m
  chart:
    spec:
      chart: rancher
      version: 2.6.4
      sourceRef:
        kind: HelmRepository
        name: rancher-server-charts
        namespace: flux-system
      interval: 5m
  values:
    hostname: "rancher.${SECRET_DOMAIN}"
    replicas: 3
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        traefik.ingress.kubernetes.io/router.tls.certresolver: leresolver