---
- name: Copy kube-vip files to first server
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ rke2_data_path }}/server/manifests/{{ item | basename | regex_replace('.j2$', '') }}"
    owner: root
    group: root
    mode: 0664
  with_fileglob:
    - "templates/kube-vip/*.j2"
