apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jellyfin-config
  namespace: jellyfin
spec:
  volumeName: pv-jellyfin-config
  storageClassName: ""
  accessModes: 
  - ReadWriteOnce
  resources:
     requests: 
      storage: 4096Mi
  selector: 
    matchLabels: 
     usage: jellyfin-config