apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jellyfin-config
  labels:
    usage: jellyfin-config
  namespace: jellyfin
spec:
  capacity:
    storage: 4096Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  #storageClassName: nfs-jellyfin-config
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /volume1/kubernetes/jellyfin/config
    server: "${NFS_SERVER}"
