---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 15m
  chart:
    spec:
      chart: cert-manager
      version: v1.8.0
      sourceRef:
        kind: HelmRepository
        name: jetstack-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    installCRDs: false
    webhook:
      enabled: true
    replicaCount: 1
    podDnsPolicy: "None"
    podDnsConfig:
      nameservers:
        - "192.168.178.5"
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
        prometheusInstance: monitoring