---
apiVersion: v1
kind: Service
metadata:
  name: &app adguard
  namespace: networking
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  type: ExternalName
  externalIPs: 192.168.178.10
  ports:
    - name: http
      port: 3000
      protocol: TCP