---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 11.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      # -- image repository
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2021.11.5
      # -- image pull policy
      pullPolicy: IfNotPresent

    # -- environment variables.
    # @default -- See below
    env:
      # -- Set the container timezone
      TZ: "Europe/Berlin"

    # -- Configures service settings for the chart. Normally this does not need to be modified.
    # @default -- See values.yaml
    service:
      main:
        ports:
          http:
            port: 8123

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.tls.certresolver: leresolver
        hosts:
          - host: "home.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
        - hosts:
            - "home.${SECRET_DOMAIN}"

    # -- Enable devices to be discoverable
    # hostNetwork: true

    # -- When hostNetwork is true set dnsPolicy to ClusterFirstWithHostNet
    # dnsPolicy: ClusterFirstWithHostNet

    securityContext:
      # -- (bool) Privileged securityContext may be required if USB devics are accessed directly through the host machine
      privileged:  false

    prometheus:
      # -- Enable and configure a Prometheus serviceMonitor for the chart under this key.
      # @default -- See values.yaml
      serviceMonitor:
        enabled: false
        portName: http
        ## See https://www.home-assistant.io/docs/authentication/ for where to find
        ## long lived access token creation under your account profile, which is
        ## needed to monitor Home Assistant
        # bearerTokenSecret:
        #   name: ""
        #   key: ""
        # interval: 1m
        # additionalLabels: {}

    # -- Configure persistence settings for the chart under this key.
    # @default -- See values.yaml
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config
      # -- Configure a hostPathMount to mount a USB device in the container.
      # @default -- See values.yaml

    # -- Enable and configure mariadb database subchart under this key.
    #    For more options see [mariadb chart documentation](https://github.com/bitnami/charts/tree/master/bitnami/mariadb)
    # @default -- See values.yaml
  
