apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homer-config
  namespace: home
spec:
  volumeName: pv-homer
  storageClassName: ""
  accessModes: 
  - ReadWriteOnce
  resources:
     requests: 
      storage: 128Mi
  selector: 
    matchLabels: 
     usage: homer