apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-homer
  labels:
    usage: homer
  namespace: home
spec:
  capacity:
    storage: 128Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /volume1/kubernetes/homer
    server: "${NFS_SERVER}"
