apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-adguard-work
  namespace: home
spec:
  volumeName: pv-adguard-work
  storageClassName: "nfs-adguard-work"
  accessModes: 
  - ReadWriteOnce
  resources:
     requests: 
      storage: 1024Mi
  selector: 
    matchLabels: 
     usage: adguard-work