# Server plan
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: server-plan
  namespace: system-upgrade
  labels:
    rke2-upgrade: server
spec:
  concurrency: 1
  channel: https://update.rke2.io/v1-release/channels/v1.24
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: In 
        values:
          - "true"
  serviceAccountName: system-upgrade
  cordon: true
  tolerations: 
    - key: node-role.kubernetes.io/control-plane
      operator: Exists 
      effect: NoSchedule
    - key: node-role.kubernetes.io/master
      operator: Exists 
      effect: NoSchedule
    - key: CriticalAddonsOnly
      operator: Exists 
      effect: NoExecute 
  upgrade:  
    image: rancher/rke2-upgrade