---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-server
  namespace: system-upgrade
spec:
  serviceAccountName: system-upgrade
  concurrency: 1
  channel: https://update.k3s.io/v1-release/channels/v1.22
 # cordon wird nicht benötigt da es nur ein Server/master in diesem Fall gibt
  cordon: true
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/master
        operator: In
        values:
          - "true"
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
    - effect: NoSchedule
      key: node-role.kubernetes.io/controlplane
      operator: Exists
  upgrade:
    image: rancher/k3s-upgrade