apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- metallb-system.yaml
- nfs-provisioner.yaml
- traefik-ingress.yaml
- jellyfin.yaml
- homer.yaml
- vaultwarden.yaml
- home-assistant.yaml
- monitoring.yaml
- uptime-kuma.yaml
- minio.yaml
- paperless.yaml
- adguard.yaml
- falco-system.yaml
- home.yaml